---
- name: Deploy web server
  hosts: all
  become: yes
  tasks:
    - name: Clonează repository-ul web
      git:
        repo: 'https://github.com/exemplu/repository.git'
        dest: /var/www/html
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes
